"""empty message

Revision ID: 9ea35a384dcf
Revises: 2c776df781c3
Create Date: 2023-08-01 01:01:31.058982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea35a384dcf'
down_revision = '2c776df781c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platos', sa.String(length=120), nullable=False),
    sa.Column('mesa', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturas')
    # ### end Alembic commands ###
